name: CD - Deploy to EC2

on:
  pull_request:
    branches:
      - develop-github-actions
    types:
      - closed
  push:
    branches:
      - develop-github-actions

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chomod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd /cicd
            git pull origin develop-github-actions
            npm install
            npm run build
            pm2 restart cicd
          EOF