name: CD - Deploy to EC2

on:
  pull_request:
    branches:
      - develop-github-actions
    types:
      - closed
  push:
    branches:
      - develop-github-actions

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
          cd /cicd
          git pull origin develop-github-actions
          npm install
          npm run build
          pm2 restart cicd
          EOF
